# Generated by Django 5.2.7 on 2025-10-05 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('yaml_content', models.TextField(help_text='Raw YAML content of the playbook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Variable name (e.g., 'ansible_python_interpreter')", max_length=100)),
                ('value', models.TextField(help_text='Variable value')),
                ('description', models.TextField(blank=True, help_text='Description of what this variable does')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Mark as sensitive to hide value in UI')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(help_text='Display name for the host', max_length=100)),
                ('hostname', models.CharField(help_text='Hostname or IP address (used as ansible_host if different from alias)', max_length=200)),
                ('port', models.PositiveIntegerField(default=22, help_text='SSH port')),
                ('username', models.CharField(help_text='SSH username', max_length=100)),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Host-specific Ansible variables')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this host is active and available')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last successful connection', null=True)),
                ('connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline'), ('unreachable', 'Unreachable')], default='unknown', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_hosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='InventoryGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Ansible group variables in JSON format')),
                ('hosts', models.ManyToManyField(blank=True, help_text='Hosts in this group', to='station.host')),
                ('parent_groups', models.ManyToManyField(blank=True, related_name='child_groups', to='station.inventorygroup')),
                ('reusable_variables', models.ManyToManyField(blank=True, help_text='Reusable variables assigned to this group', related_name='groups', to='station.variable')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('log_output', models.TextField(blank=True, help_text='Full output from ansible-playbook command')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='station.playbook')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('private_key', models.TextField(help_text='SSH private key content')),
                ('public_key', models.TextField(blank=True, help_text='SSH public key content')),
                ('passphrase_encrypted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='ssh_keys', to='station.inventorygroup')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_key',
            field=models.ForeignKey(blank=True, help_text='Primary SSH key for authentication. If null, password-based or other authentication is assumed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='station.sshkey'),
        ),
        migrations.AddField(
            model_name='host',
            name='reusable_variables',
            field=models.ManyToManyField(blank=True, help_text='Reusable variables assigned to this host', related_name='hosts', to='station.variable'),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('members', models.ManyToManyField(blank=True, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='variable',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='station.workspace'),
        ),
        migrations.AddField(
            model_name='sshkey',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to='station.workspace'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='station.workspace'),
        ),
        migrations.AddField(
            model_name='inventorygroup',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_groups', to='station.workspace'),
        ),
        migrations.AddField(
            model_name='host',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='station.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('workspace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='sshkey',
            unique_together={('workspace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorygroup',
            unique_together={('workspace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('workspace', 'hostname', 'port')},
        ),
    ]
