version: '3.8'

services:
#  web:
#    build: .
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    env_file:
#      - .env

  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=astation_user
      - POSTGRES_PASSWORD=astation_password123
      - POSTGRES_DB=mydatabase

#  celery:
#    build: .
#    command: celery -A app.celery_worker.celery worker --loglevel=info
#    depends_on:
#      - db
#      - redis
#
#  redis:
#    image: "redis:alpine"

volumes:
  postgres_data:
