"""jobs

Revision ID: e7c65c9da781
Revises: 81f887250de4
Create Date: 2025-11-21 18:16:38.869855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c65c9da781'
down_revision = '81f887250de4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ansible_version', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ansible_version')
    # ### end Alembic commands ###